# Generated by src/generator/generate.py — review before committing.
# Story: stories/login.txt

from src.config import settings
from src.framework.page import BasePage


def test_valid_credentials_reach_inventory(base_page: BasePage) -> None:
    """A user with valid credentials lands on the inventory page after login"""
    base_page.navigate(settings.base_url)
    base_page.resolve("username_input").fill("standard_user")
    base_page.resolve("password_input").fill("secret_sauce")
    base_page.resolve("login_button").click()
    base_page.resolve("inventory_container").wait_for()

def test_invalid_password_shows_error(base_page: BasePage) -> None:
    """An invalid password shows an error message on the login page"""
    base_page.navigate(settings.base_url)
    base_page.resolve("username_input").fill("standard_user")
    base_page.resolve("password_input").fill("wrong_password")
    base_page.resolve("login_button").click()
    base_page.resolve("error_message").wait_for()
