"""Deterministic code generator: TestPlan -> pytest file. No LLM involved."""

from src.generator.schema import Step, TestCase, TestPlan

_HEADER = """\
# Generated by src/generator/generate.py — review before committing.
# Story: {story_path}

from src.config import settings
from src.framework.page import BasePage

"""


def render(plan: TestPlan, story_path: str) -> str:
    sections = [_HEADER.format(story_path=story_path)]
    for test in plan.tests:
        sections.append(_render_test(test))
    return "\n".join(sections)


def _render_test(test: TestCase) -> str:
    lines = [
        f"def {test.test_name}(base_page: BasePage) -> None:",
        f'    """{test.description}"""',
    ]
    for step in test.steps:
        lines.append("    " + _render_step(step))
    lines.append("")
    return "\n".join(lines)


def _render_step(step: Step) -> str:
    if step.action == "navigate":
        return "base_page.navigate(settings.base_url)"
    if step.action == "fill":
        return f'base_page.resolve("{step.target}").fill("{step.value}")'
    if step.action == "click":
        return f'base_page.resolve("{step.target}").click()'
    if step.action == "assert_visible":
        return f'base_page.resolve("{step.target}").wait_for()'
    if step.action == "assert_text":
        return (
            f'assert "{step.value}" in '
            f'(base_page.resolve("{step.target}").text_content() or "")'
        )
    return f"# unknown action: {step.action}"
